AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Game API SAM Template

Parameters:
  AppEnvironment:
    Type: String
    Default: production
    Description: The application environment (e.g., development, staging, production)
  ProdDynamoDBTable:
    Type: String
    Default: prod-table
    Description: The DynamoDB table name
  ProdDynamoDBRegion:
    Type: String
    Default: us-east-1
    Description: The DynamoDB region
  ProdDynamoDBEndpoint:
    Type: String
    Default: https://dynamodb.us-east-1.amazonaws.com
    Description: The DynamoDB endpoint (dynamically determined by region)
  DevDynamoDBTable:
    Type: String
    Default: dev-table
    Description: The DynamoDB table name
  DevDynamoDBRegion:
    Type: String
    Default: us-east-1
    Description: The DynamoDB region
  DevDynamoDBEndpoint:
    Type: String
    Default: http://host.docker.internal:8000
    Description: The DynamoDB endpoint
  ExistingUserPoolId:
    Type: String
    Description: The ID of the existing Cognito User Pool

Globals:
  Function:
    Timeout: 30
    Runtime: provided.al2023
    Environment:
      Variables:
        APP_ENV: !Ref AppEnvironment
        DYNAMODB_TABLE: !If 
          - IsProduction
          - !Ref ProdDynamoDBTable
          - !Ref DevDynamoDBTable
        DYNAMODB_ENDPOINT: !If 
          - IsProduction
          - !Ref ProdDynamoDBEndpoint
          - !Ref DevDynamoDBEndpoint
        DYNAMODB_REGION: !If 
          - IsProduction
          - !Ref ProdDynamoDBRegion
          - !Ref DevDynamoDBRegion
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${ExistingUserPoolId}
          AuthorizationScopes:
            - email
            - openid


Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/user/
      Handler: bootstrap.router
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: GET
        GetUsersByPrefix:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        GetUserGameStats:
          Type: Api
          Properties:
            Path: /users/{userId}/games/{gameId}/stats
            Method: GET
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: PUT
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If 
              - IsProduction
              - !Ref ProdDynamoDBTable
              - !Ref DevDynamoDBTable

  GameFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/game/
      Handler: bootstrap.router
      Events:
        GetGame:
          Type: Api
          Properties:
            Path: /games/{gameId}
            Method: GET
        GetGameLeaderboard:
          Type: Api
          Properties:
            Path: /games/{gameId}/leaderboard/{attribute}
            Method: GET
        CreateGame:
          Type: Api
          Properties:
            Path: /games
            Method: POST
        UpdateGame:
          Type: Api
          Properties:
            Path: /games/{gameId}
            Method: PUT
        DeleteGame:
          Type: Api
          Properties:
            Path: /games/{gameId}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If 
              - IsProduction
              - !Ref ProdDynamoDBTable
              - !Ref DevDynamoDBTable

  MatchFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/match/
      Handler: bootstrap.router
      Events:
        GetMatch:
          Type: Api
          Properties:
            Path: /matches/{gameId}/{matchId}/{dateId}
            Method: GET
        GetMatches:
          Type: Api
          Properties:
            Path: /matches
            Method: GET
        CreateMatch:
          Type: Api
          Properties:
            Path: /matches
            Method: POST
        UpdateMatch:
          Type: Api
          Properties:
            Path: /matches/{gameId}/{matchId}/{dateId}
            Method: PUT
        DeleteMatch:
          Type: Api
          Properties:
            Path: /matches/{gameId}/{matchId}/{dateId}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !If 
              - IsProduction
              - !Ref ProdDynamoDBTable
              - !Ref DevDynamoDBTable

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ExistingUserPoolId
      ClientName: !Sub ${AWS::StackName}-UserPoolClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      EnableTokenRevocation: true
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days

Outputs:
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  GameFunction:
    Description: "Game Lambda Function ARN"
    Value: !GetAtt GameFunction.Arn
  MatchFunction:
    Description: "Match Lambda Function ARN"
    Value: !GetAtt MatchFunction.Arn
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref ExistingUserPoolId
  CognitoUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient

Conditions:
  IsProduction: !Equals 
    - !Ref AppEnvironment
    - "production"
